---
info:
  application: RentMe connected trucks Demo
  show: Spring One 2GX 2015

logging:
  level:
    com.netflix.discovery: 'OFF'

endpoints:
  restart: enabled

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10

ribbon:
  ServerListRefreshInterval: 5000

hystrix.command.default.execution.isolation.strategy: SEMAPHORE

---
spring:
  profiles: cloud

---
spring:
  profiles: dev
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
